### ISSUE TITLE
Module doesn't work with Edgeswitch version 1.8.2

### ISSUE THREAD

**Issue by Luca232000** [f-bor/ansible-edgeswitch#1]
I tried to configure my EdgeSwitch with an ansible playbook but I couldn't get it working.

Here my playbook:
```
- hosts: edgeswitch
  connection: network_cli
  tasks:   
    - name: Create vlan
      edgeswitch_vlan:
        vlan_id: 100
        name: test
        state: present
```

I am getting this error:
 ```
   "Unable to decode JSON from response to {0}({1}). Received '{2}'.".format(name, params, out)

fatal: [edgeswitch]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "auto_exclude": null,
            "auto_tag": null,
            "auto_untag": null,
            "excluded_interfaces": null,
            "name": "test",
            "purge": false,
            "state": "present",
            "tagged_interfaces": null,
            "untagged_interfaces": null,
            "vlan_id": "100"
        }
    },
    "msg": "Unable to decode JSON from response to run_commands(commands=['vlan database', 'vlan 100', 'vlan name 100 \"test\"', 'exit'], check_rc=False). Received 'None'."
}

```
